# Colors (PaperColor - Light)

# Default colors
[colors.primary]
background = '#e791bf'
foreground = '#444444'


[colors.cursor]
text = '#FFFFFF'
cursor = '#444444'
[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"
# Normal colors
[colors.normal]
black   = '#eeeeee'
red     = '#af0000'
green   = '#008700'
yellow  = '#5f8700'
blue    = '#0087af'
magenta = '#878787'
cyan    = '#005f87'
white   = '#444444'

# Bright colors
[colors.bright]
black   = '#bcbcbc'
red     = '#d70000'
green   = '#d70087'
yellow  = '#8700af'
blue    = '#d75f00'
magenta = '#d75f00'
cyan    = '#005faf'
white   = '#005f87'


[font]
normal = {family = "JetBrainsMono", style="Bold"}
bold = {family="JetBrainsMono", style="BoldItalic"}
italic = {family="JetBrainsMono", style="Italic"}
size = 12 

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

