# Default colors
[colors.primary]
background = '#EAEFF2'
foreground = '#A16AE8'


[colors.cursor]
text = '#EAEFF2'
cursor = '#444444'

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

# Normal colors
[colors.normal]
black   = '#EAEFF2'
red     = '#af0000'
green   = '#00B1B0'
yellow  = '#5f8700'
blue    = '#FB6B90'
magenta = '#878787'
cyan    = '#005f87'
white   = '#FFFFFF'

# Bright colors
[colors.bright]
black   = '#bcbcbc'
red     = '#d70000'
green   = '#d70087'
yellow  = '#8700af'
blue    = '#d75f00'
magenta = '#d75f00'
cyan    = '#005faf'
white   = '#005f87'


[font]
normal = {family = "MesloLGS NF", style="Bold"}
bold = {family="MesloLGS NF", style="BoldItalic"}
italic = {family="MesloLGS NF", style="Italic"}
size = 12 

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

